packages:
- jaeger-types
- jaeger-opentracing-tags
- jaeger-utils
- monad-jaeger
- monad-logger-jaeger
- jaeger-sampler
- logging-effect-jaeger
- wai-jaeger
- servant-jaeger
- monad-jaeger-metrics-ekg

resolver: lts-14.22

extra-deps:
- pinch-0.3.5.0@sha256:0da4940423cdb4c2536aabf0df5979eff0e137132b3686405c3758418fd08589,3931

allow-newer: true
